"use client"

import React, { createContext, useContext, useState, useEffect } from "react"

type Language = "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "header.season": "Season 2",
    "header.openSource": "Open Source",
    "header.tooltip.openSource": "AI-powered Stock Analysis & Trading System • MIT License",
    "header.startDate": "Start: 2025.09.29",
    "header.updated": "Updated",
    "header.realtimeUpdate": "Real-time Update",
    "header.dashboard": "Dashboard",
    "header.aiDecisions": "AI Holdings",
    "header.trading": "Trades",
    "header.watchlist": "Watchlist",
    "header.insights": "Insights",
    "header.tooltip.github": "GitHub Repository",
    "header.tooltip.community": "GitHub Discussions",
    "header.tooltip.theme": "Toggle Theme",

    // Loading
    "loading.text": "Loading data...",

    // Tables
    "table.realPortfolio": "Real Trading Portfolio",
    "table.simulator": "Prism Simulator",
    "table.stock": "Stock",
    "table.stockName": "Stock Name",
    "table.sector": "Sector",
    "table.quantity": "Qty",
    "table.avgPrice": "Avg Price",
    "table.currentPrice": "Current",
    "table.buyPrice": "Buy Price",
    "table.targetPrice": "Target",
    "table.stopLoss": "Stop Loss",
    "table.profitRate": "Return",
    "table.profitAmount": "P&L",
    "table.totalValue": "Value",
    "table.holdingDays": "Days",
    "table.period": "Period",
    "table.weight": "Weight",
    "table.unknown": "Unknown",

    // Metrics Cards - Real Trading
    "metrics.realTrading": "Real Trading (Season 2)",
    "metrics.realTotalAssets": "Real Total Assets",
    "metrics.realHoldingsProfit": "Real Holdings P&L",
    "metrics.realProfitDist": "Real Profit Distribution",
    "metrics.startAmount": "Start Amount",
    "metrics.deposit": "Cash",
    "metrics.stocks": " stocks",
    "metrics.assetsDesc": "Holdings + Cash",
    "metrics.holdingsProfitDesc": "Current holdings P&L",
    "metrics.excludeRealized": "Unrealized only",
    "metrics.profitDistDesc": "Profit/Loss breakdown",
    "metrics.cashAndStability": "Cash & Portfolio Stability",
    "metrics.cashRatio": "Cash Ratio",
    "metrics.investmentRatio": "Investment Ratio",
    "metrics.cashStabilityDesc": "Cash balance & allocation",
    "metrics.fullyInvested": "Fully invested",
    "metrics.wins": "W",
    "metrics.losses": "L",
    "metrics.breakEven": "Even",
    "metrics.totalStocks": "Total",
    "metrics.winRate": "Win Rate",

    // Metrics Cards - Simulator
    "metrics.simulator": "Prism Simulator",
    "metrics.simSoldProfit": "Sim Sold Total Return",
    "metrics.simAvgHoldingDays": "Sim Avg Holding Days",
    "metrics.simCurrentProfit": "Sim Current Holdings Return",
    "metrics.waitingSell": "Awaiting sale",
    "metrics.onlyHolding": "Only holdings exist",
    "metrics.updateOnSell": "Updates on sale",
    "metrics.soldProfitDesc": "Total return from sold stocks",
    "metrics.sold": "sold",
    "metrics.soldBasis": " sold basis",
    "metrics.needStrategy": "Review strategy",
    "metrics.avgHoldingDesc": "Avg days until sale",
    "metrics.holding": "holding",
    "metrics.avgProfit": "Avg",
    "metrics.slotUsage": "Slot usage",
    "metrics.currentProfitDesc": "Total return from current holdings",
    "metrics.started": "Started",
    "metrics.elapsed": "d elapsed",

    // Operating Costs
    "costs.title": "Project Operating Costs Transparency",
    "costs.description": "Disclosing last month's costs for sustainable open-source operations",
    "costs.serverHosting": "Server Hosting",
    "costs.basis": "as of",
    "costs.perMonth": "/ mo",
    "costs.year": "",
    "costs.month": "",
    "costs.helpQuestion": "Has this project helped you?",
    "costs.sponsorDesc": "Support sustainable development via GitHub Sponsor",
    "costs.becomeSponsor": "Become a Sponsor",

    // Badges
    "badge.realTrading": "Real Trading",
    "badge.aiSimulation": "AI Simulation",
    "badge.season2": "Season 2",
    "badge.koreanInvestment": "Korea Investment & Securities",

    // Date/Time
    "date.year": "-",
    "date.month": "-",
    "date.day": "",

    // Common
    "common.won": "KRW",
    "common.krw": "₩",
    "common.percent": "%",
    "common.days": "d",
    "common.trades": "trades",
    "common.shares": " shares",
    "common.other": "Others",
    "common.unclassified": "Unclassified",
    "metrics.totalReturn": "Total Return",
    "metrics.avgReturn": "Avg Return",
    "metrics.avgHoldingDays": "Avg Days",
    "metrics.totalTrades": "Total Trades",

    // Charts
    "chart.prismReturn": "Prism Simulator (Realized)",
    "chart.returnComparisonKospi": "Return Comparison (S&P 500)",
    "chart.returnComparisonKosdaq": "Return Comparison (NASDAQ)",
    "chart.returnComparisonSP500": "Return Comparison (S&P 500)",
    "chart.returnComparisonNasdaq": "Return Comparison (NASDAQ)",
    "chart.market": "Market",
    "chart.prism": "Prism",
    "chart.return": "Return",
    "chart.index": "Index",

    // Market Selector
    "market.kr": "Korea",
    "market.us": "US",
    "market.selector.title": "Select Market",
    "market.us.realTrading": "US Real Trading",
    "market.us.simulator": "US Simulator",
    "market.us.season": "Season 1",

    // Stock Detail Modal
    "modal.stockDetail": "Stock Details",
    "modal.close": "Close",
    "modal.currentPrice": "Current Price",
    "modal.profitRate": "Return",
    "modal.holdingInfo": "Holding Info",
    "modal.holdingQuantity": "Quantity",
    "modal.avgBuyPrice": "Avg Buy Price",
    "modal.evaluationAmount": "Valuation",
    "modal.evaluationPL": "P&L",
    "modal.portfolioWeight": "Portfolio Weight",
    "modal.tradingInfo": "Trading Info",
    "modal.buyDate": "Buy Date",
    "modal.buyPrice": "Buy Price",
    "modal.targetPrice": "Target",
    "modal.stopLossPrice": "Stop Loss",
    "modal.riskRewardRatio": "Risk/Reward Ratio",
    "modal.expectedReturn": "Expected Return",
    "modal.expectedLoss": "Expected Loss",
    "modal.holdingDays": "Days Held",
    "modal.lastUpdate": "Last Update",
    "modal.aiTradingScenario": "AI Trading Scenario",
    "modal.buyDecision": "Buy Decision",
    "modal.maxPortfolioSize": "Max Portfolio Size",
    "modal.keyPriceLevels": "Key Price Levels",
    "modal.sellTriggers": "Sell Triggers",
    "modal.holdConditions": "Hold Conditions",
    "modal.portfolioContext": "Portfolio Context",
    "modal.basicInfo": "Basic Info",
    "modal.buyInfo": "Buy Info",
    "modal.currentStatus": "Current Status",
    "modal.targetStopLoss": "Target/Stop Loss",
    "modal.investmentPeriod": "Investment Period",
    "modal.investmentRationale": "Investment Rationale",
    "modal.tradingScenarios": "Trading Scenarios",
    "modal.keyLevels": "Key Levels",
    "modal.portfolioAnalysis": "Portfolio Analysis",
    "modal.valuationAnalysis": "Valuation Analysis",
    "modal.sectorOutlook": "Sector Outlook",
    "modal.marketCondition": "Market Condition",
    "modal.primarySupport": "Primary Support",
    "modal.secondarySupport": "Secondary Support",
    "modal.primaryResistance": "Primary Resistance",
    "modal.secondaryResistance": "Secondary Resistance",
    "modal.volumeBaseline": "Volume Baseline",
    "modal.primarySupportShort": "1st Support",
    "modal.secondarySupportShort": "2nd Support",
    "modal.primaryResistanceShort": "1st Resistance",
    "modal.secondaryResistanceShort": "2nd Resistance",
    "modal.buyScore": "Buy Score",

    // AI Decisions Page
    "aiDecisions.title": "AI Holdings Analysis",
    "aiDecisions.description": "AI analysis of current holdings for sell/hold decisions",
    "aiDecisions.lastAnalysis": "Last Analysis",
    "aiDecisions.sell": "Sell",
    "aiDecisions.hold": "Hold",
    "aiDecisions.confidence": "Confidence",
    "aiDecisions.technicalTrend": "Technical Trend",
    "aiDecisions.volumeAnalysis": "Volume Analysis",
    "aiDecisions.marketCondition": "Market Condition",
    "aiDecisions.timeFactor": "Time Factor",
    "aiDecisions.portfolioAdjustment": "Portfolio Adjustment",
    "aiDecisions.portfolioAdjustmentNeeded": "Portfolio Adjustment Needed",
    "aiDecisions.maintainStrategy": "Maintain Current Strategy",
    "aiDecisions.newTargetPrice": "New Target Price",
    "aiDecisions.newStopLoss": "New Stop Loss",
    "aiDecisions.urgency": "Urgency",
    "aiDecisions.reason": "Reason",
    "aiDecisions.noData": "No analysis data available",
    "aiDecisions.pageDescription": "Daily AI analysis records for held stocks",
    "aiDecisions.totalAnalysis": "Total",
    "aiDecisions.recordsCount": " analyses",
    "aiDecisions.totalAnalysisRecords": "Total Analysis Records",
    "aiDecisions.records": " records",
    "aiDecisions.allHoldDecisions": "All hold decisions",
    "aiDecisions.adjustmentNeeded": "Adjustment needed",
    "aiDecisions.portfolioRebalanceRecommended": "Portfolio rebalance recommended",
    "aiDecisions.analyzedStocksCount": "Analyzed Stocks Count",
    "aiDecisions.stocksCount": " stocks",
    "aiDecisions.cumulativeBasis": "Cumulative basis",
    "aiDecisions.analysisCount": " analyses",
    "aiDecisions.holdMaintain": "Hold Maintain",
    "aiDecisions.analysisTime": "Analysis time",
    "aiDecisions.analysisPricePoint": "Analysis price point",
    "aiDecisions.aiJudgementBasis": "AI Judgement Basis",
    "aiDecisions.analysisSummary": "Analysis Summary",
    "aiDecisions.marketImpact": "Market Impact",
    "aiDecisions.timeFactor2": "Time Factor",
    "aiDecisions.portfolioAdjustmentSection": "Portfolio Adjustment",
    "aiDecisions.newTargetPriceHistory": "New Target Price History",
    "aiDecisions.newStopLossHistory": "New Stop Loss History",
    "aiDecisions.noAnalysisDataYet": "No AI holding analysis data yet.",

    // Trading History Page
    "trading.title": "Trading History",
    "trading.description": "Completed trade analysis & AI scenario comparison",
    "trading.totalTrades": "Total Trades",
    "trading.totalProfit": "Total P&L",
    "trading.avgProfit": "Avg Return",
    "trading.avgHoldingDays": "Avg Holding",
    "trading.avgHoldingDaysShort": "Avg Days",
    "trading.sellDate": "Sell Date",
    "trading.buyDate": "Buy Date",
    "trading.buyPrice": "Buy Price",
    "trading.sellPrice": "Sell Price",
    "trading.profitRate": "Return",
    "trading.holdingDays": "Days",
    "trading.holdingPeriod": "Holding Period",
    "trading.filters": "Filters",
    "trading.all": "All",
    "trading.profit": "Profit",
    "trading.loss": "Loss",
    "trading.scenario": "Scenario",
    "trading.noData": "No trading history yet.",
    "trading.times": " trades",
    "trading.winRate": "Win Rate",
    "trading.detailedHistory": "Detailed History",
    "trading.aiTargetPrice": "AI Target",
    "trading.targetAchievementRate": "Target Achievement",
    "trading.aiInvestmentRationale": "AI Investment Rationale",
    "trading.aiScenarioDetails": "AI Trading Scenario Details",
    "trading.pastMarketCondition": "Market Condition at Time",
    "trading.tradeCount": " trades",
    "trading.completedTrades": "Completed trades",
    "trading.winningTradeRatio": "Winning trade ratio",
    "trading.avgPerformancePerTrade": "Avg performance per trade",
    "trading.daysFromBuyToSell": "Days from buy to sell",
    "trading.bestTrade": "Best Trade",
    "trading.worstTrade": "Worst Trade",
    "trading.sectorPerformanceTop3": "Sector Performance TOP 3",
    "trading.periodPerformance": "Period Performance",
    "trading.daysHeld": " days held",
    "trading.avgWinRate": "Avg Win",
    "trading.avgLossRate": "Avg Loss",
    "trading.winningTradesAvg": " winning trades avg",
    "trading.losingTradesAvg": " losing trades avg",
    "trading.profitFactor": "Profit Factor",
    "trading.profitFactorDesc": "Total profit ÷ Total loss (>1 = profitable)",
    "trading.riskRewardRatio": "Risk/Reward",
    "trading.riskRewardDesc": "Avg win ÷ Avg loss",
    "trading.maxWinStreak": "Max Win Streak",
    "trading.maxWinStreakDesc": "Consecutive winning trades",
    "trading.consecutive": " in a row",
    "trading.avgWinShort": "Avg Win",
    "trading.avgLossShort": "Avg Loss",
    "trading.tradeCountShort": "",
    "trading.mdd": "MDD",
    "trading.mddDesc": "Maximum Drawdown (Peak to trough decline)",
    "trading.alpha": "Alpha",
    "trading.alphaDesc": "Excess return vs market",
    "trading.beta": "Beta",
    "trading.betaDesc": "Volatility vs market (1 = same as market)",
    "trading.sharpeRatio": "Sharpe Ratio",
    "trading.sharpeDesc": "Risk-adjusted return (higher is better)",
    "trading.informationRatio": "Information Ratio",
    "trading.informationRatioDesc": "Excess return per tracking error",
    "trading.riskAdjustedMetrics": "Risk-Adjusted Metrics",
    "trading.dataPeriod": "Data Period",
    // Tooltip explanations
    "trading.profitFactorTooltip": "Total profit divided by total loss. Shows how many times your winners exceed your losers in absolute terms.",
    "trading.profitFactorGood": "✓ Above 1.5: Excellent (Profits are 1.5x losses)",
    "trading.profitFactorNeutral": "• 1.0-1.5: Average (Profits exceed losses)",
    "trading.profitFactorBad": "✗ Below 1.0: Warning (Losses exceed profits)",
    "trading.riskRewardTooltip": "Average winning trade divided by average losing trade. Shows how much you win on average compared to how much you lose.",
    "trading.riskRewardGood": "✓ Above 2.0: Excellent (Wins are 2x losses)",
    "trading.riskRewardNeutral": "• 1.0-2.0: Average (Wins exceed losses)",
    "trading.riskRewardBad": "✗ Below 1.0: Warning (Losses exceed wins)",
    "trading.mddTooltip": "Maximum Drawdown. The largest peak-to-trough decline during the investment period. Shows your worst-case scenario loss.",
    "trading.mddGood": "✓ Below 10%: Excellent (Stable management)",
    "trading.mddNeutral": "• 10%-20%: Average (Normal volatility)",
    "trading.mddBad": "✗ Above 20%: Warning (High volatility)",
    "trading.alphaTooltip": "Excess return above the market (S&P 500). A key measure of investment skill - shows how much more (or less) you earned compared to the market.",
    "trading.alphaGood": "✓ Positive (+): Beating the market",
    "trading.alphaBad": "✗ Negative (-): Underperforming the market",
    "trading.betaTooltip": "Measures volatility relative to the market. Shows how much your portfolio moves when the market moves 1%.",
    "trading.betaLow": "◐ Below 1: Lower volatility (More stable than market)",
    "trading.betaNeutral": "• 1.0: Same volatility as market",
    "trading.betaHigh": "◐ Above 1: Higher volatility (More aggressive than market)",
    "trading.sharpeTooltip": "Risk-adjusted return. Shows how much excess return (above risk-free rate like savings interest) you achieved per unit of risk taken.",
    "trading.sharpeGood": "✓ Above 1.0: Excellent (High return for risk taken)",
    "trading.sharpeNeutral": "• 0-1.0: Average (Acceptable level)",
    "trading.sharpeBad": "✗ Below 0: Warning (Worse than risk-free assets)",
    "trading.irTooltip": "Excess return over benchmark (S&P 500) divided by tracking error. Evaluates how consistently you beat the market.",
    "trading.irGood": "✓ Above 0.5: Excellent (Consistently beats market)",
    "trading.irNeutral": "• 0-0.5: Average (Slight outperformance)",
    "trading.irBad": "✗ Below 0: Warning (Underperforming market)",

    // Watchlist Page
    "watchlist.title": "Watchlist",
    "watchlist.description": "AI-analyzed investment candidates (Last 1 month)",
    "watchlist.totalStocks": "Total Stocks",
    "watchlist.stocksCount": " stocks",
    "watchlist.highestScore": "Highest Score",
    "watchlist.avgScore": "Avg Score",
    "watchlist.recentWeek": "Last 7 days",
    "watchlist.scoreUnit": " pts",
    "watchlist.entry": "Entry",
    "watchlist.watch": "No Entry",
    "watchlist.entryChecklist": "Entry Checklist",
    "watchlist.rejectionReason": "Rejection Reason",
    "watchlist.reason": "Reason",
    "watchlist.analyzedDate": "Analyzed",
    "watchlist.buyScore": "Buy Score",
    "watchlist.currentPrice": "Current",
    "watchlist.targetPrice": "Target",
    "watchlist.stopLoss": "Stop Loss",
    "watchlist.tradingRationale": "Trading Rationale",
    "watchlist.noData": "No watchlist items yet.",
    "watchlist.mostPromising": "Most promising stock",
    "watchlist.outOf10": "Out of 10",
    "watchlist.recentlyAnalyzed": "Recently analyzed",
    "watchlist.sectorDistributionTop3": "Sector Distribution TOP 3",
    "watchlist.analyses": " analyses",
    "watchlist.aiAnalysisDetails": "AI Analysis Details",
    "watchlist.copyToClipboard": "Copy to Clipboard",
    "watchlist.lastMonthAnalysis": "Last month analysis",
    "watchlist.decision": "Decision",
    "watchlist.stocksUnit": " stocks",

    // Trading Insights Page
    "insights.title": "Trading Insights",
    "insights.description": "Trigger performance analysis, AI trading principles, lessons, and accumulated intuitions",
    "insights.category.performance": "Performance Analysis",
    "insights.category.wisdom": "Trading Wisdom",
    "insights.principles": "Universal Principles",
    "insights.principlesDescription": "Core principles applicable to all trades",
    "insights.journal": "Trading Journal",
    "insights.journalDescription": "Detailed records written by AI after trade completion",
    "insights.intuitions": "Accumulated Intuitions",
    "insights.intuitionsDescription": "Long-term insights extracted from repeated patterns",
    "insights.summary.totalPrinciples": "Total Principles",
    "insights.summary.highPriority": "High Priority",
    "insights.summary.avgProfit": "Avg Profit",
    "insights.summary.totalTrades": "Total Trades",
    "insights.summary.totalIntuitions": "Total Intuitions",
    "insights.summary.avgConfidence": "Avg Confidence",
    "insights.priority.high": "High",
    "insights.priority.medium": "Medium",
    "insights.priority.low": "Low",
    "insights.scope.universal": "Universal",
    "insights.scope.sector": "Sector",
    "insights.scope.market": "Market",
    "insights.condition": "Condition",
    "insights.action": "Action",
    "insights.reason": "Reason",
    "insights.confidence": "Confidence",
    "insights.supportingTrades": "Supporting Trades",
    "insights.situationAnalysis": "Situation Analysis",
    "insights.judgmentEvaluation": "Judgment Evaluation",
    "insights.lessons": "Lessons",
    "insights.patternTags": "Pattern Tags",
    "insights.oneLine": "One-line Summary",
    "insights.category": "Category",
    "insights.insight": "Insight",
    "insights.successRate": "Success Rate",
    "insights.supportingTrades": "Supporting Trades",
    "insights.noData": "No trading insights data available yet.",
    "insights.noPrinciples": "No principles extracted yet.",
    "insights.noJournal": "No trading journal entries yet.",
    "insights.noIntuitions": "No intuitions accumulated yet.",
    "insights.layer": "Layer",
    "insights.holdingDays": "Holding Days",
    "insights.profitRate": "Profit Rate",
    "insights.tradeDate": "Trade Date",

    // Performance Analysis
    "insights.performance.title": "Trigger Performance Analysis",
    "insights.performance.description": "Track 7/14/30 day price changes of analyzed stocks",
    "insights.performance.overview": "Tracking Status",
    "insights.performance.total": "Total Tracked",
    "insights.performance.completed": "Completed",
    "insights.performance.pending": "Pending",
    "insights.performance.inProgress": "In Progress",
    "insights.performance.traded": "Traded",
    "insights.performance.watched": "Watched",
    "insights.performance.triggerType": "Watched Stocks by Trigger Type",
    "insights.performance.rrAnalysis": "Risk/Reward Threshold Analysis",
    "insights.performance.missedOpportunities": "Missed Opportunities",
    "insights.performance.avoidedLosses": "Avoided Losses",
    "insights.performance.recommendations": "Data-Driven Recommendations",
    "insights.performance.avgReturn": "Avg Return",
    "insights.performance.winRate": "Win Rate",
    "insights.performance.count": "Count",
    "insights.performance.significant": "Statistically Significant",
    "insights.performance.notSignificant": "Not Significant",
    "insights.performance.noData": "No performance tracking data yet",
    "insights.performance.noDataHint": "Data will be available once stock tracking completes",
    "insights.performance.tradedRate": "Trade Rate",
    "insights.performance.day7": "7D",
    "insights.performance.day14": "14D",
    "insights.performance.day30": "30D",
    "insights.performance.range": "Range",
    "insights.performance.allAvg": "All Avg",
    "insights.performance.watchedAvg": "Watched Avg",
    "insights.performance.skipReason": "Skip Reason",
    "insights.performance.analyzedPrice": "Analyzed Price",
    "insights.performance.trackedPrice": "Tracked Price",
    "insights.performance.returnRate": "Return",
    // Tooltip translations
    "insights.performance.tooltip.completed": "Stocks with 30 days passed since analysis (tracking complete)",
    "insights.performance.tooltip.pending": "Stocks with less than 7 days since analysis (awaiting tracking)",
    "insights.performance.tooltip.inProgress": "Stocks between 7-30 days since analysis (tracking in progress)",
    "insights.performance.tooltip.traded": "Number of stocks actually purchased after analysis",
    "insights.performance.tooltip.watched": "Number of stocks watched without purchasing after analysis",
    "insights.performance.tooltip.dayReturn": "Average return N days after analysis (based on completed tracking)",
    "insights.performance.tooltip.winRate": "Percentage of stocks with positive return after 30 days",
    "insights.performance.tooltip.tradedRate": "Percentage of this trigger type that led to actual trades",

    // Trigger Reliability Card
    "insights.triggerReliability.title": "Trigger Reliability",
    "insights.triggerReliability.description": "Which signals can you trust? Cross-analysis of accuracy, trading, and principles",
    "insights.triggerReliability.bestTrigger": "Best Trigger",
    "insights.triggerReliability.grade": "Grade",
    "insights.triggerReliability.analysisAccuracy": "Analysis Accuracy",
    "insights.triggerReliability.actualTrading": "Actual Trading",
    "insights.triggerReliability.principles": "Related Principles",
    "insights.triggerReliability.recommendation": "Recommendation",
    "insights.triggerReliability.tracked": "Tracked",
    "insights.triggerReliability.completed": "Completed",
    "insights.triggerReliability.trades": "Trades",
    "insights.triggerReliability.winRate": "Win Rate",
    "insights.triggerReliability.avgReturn": "Avg Return",
    "insights.triggerReliability.profitFactor": "PF",
    "insights.triggerReliability.noData": "No trigger reliability data available yet.",
    "insights.triggerReliability.gradeA": "High Confidence",
    "insights.triggerReliability.gradeB": "Good",
    "insights.triggerReliability.gradeC": "Caution",
    "insights.triggerReliability.gradeD": "Insufficient Data",
    "insights.triggerReliability.miniBadge": "Most Reliable Trigger",
    "insights.triggerReliability.viewDetails": "View Details",

    // Footer
    "footer.description": "AI-powered Stock Analysis & Trading System",
    "footer.openSource": "Fully Open Source & Free • MIT License",
    "footer.features": "Key Features",
    "footer.feature1": "12 AI Agents Collaborative Analysis",
    "footer.feature2": "Automated Surge Stock Detection & Reports",
    "footer.feature3": "Trading Simulation & Auto Trading",
    "footer.feature4": "Real-time Performance Dashboard",
    "footer.links": "Quick Links",
    "footer.sourceCode": "Source Code & Issues",
    "footer.communityDesc": "Surge Stocks & Analysis Reports",
    "footer.stars": "250+ Stars in 10 weeks",
    "footer.disclaimer": "⚠️ The analysis information provided by this system is for reference only and is not intended as investment advice. All investment decisions and resulting profits/losses are the sole responsibility of the investor.",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en")

  // Load language from localStorage on mount
  useEffect(() => {
    const stored = localStorage.getItem("language") as Language
    if (stored === "en") {
      setLanguageState(stored)
    }
  }, [])

  // Save language to localStorage when it changes
  const setLanguage = (lang: Language) => {
    if (lang !== "en") {
      return
    }
    setLanguageState("en")
    localStorage.setItem("language", "en")
  }

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
